config/routes.rb
Rails.application.routes.draw do
  resources :activities

  get "/stat_medium", to: "stat#medium"
  get "/stat_activity", to: "stat#activity"
  get "/stat_activity_medium", to: "stat#activity_medium"
end

app/models/activity.rb
class Activity < ApplicationRecord
  has_many :visitors
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/visitor.rb
class Visitor < ApplicationRecord
  CHANNELS = [:cpc, :organic, :affiliate, :email]

  enum medium: CHANNELS

  belongs_to :activity
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: :show

  def index
    @activities = Activity.joins(:visitors)
                    .select("title, count(visitors.id) as visits_count")
                    .group("activities.id")
                    .order("visits_count, title")
                    .page(params[:page]).per(10)
  end

  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/stat_controller.rb
class StatController < ApplicationController
  before_action do
    @q = Visitor.ransack(params[:q])
  end
  def medium
    @channels = @q.result.group(:medium).joins(:activity)
                  .select("medium, count(user_id) as visitors_count, sum(arpu) as arpu_sum")
                  .order("visitors_count desc, medium asc")
  end

  def activity
    @activities = @q.result.joins(:activity).group("activities.id")
                    .select("title, sum(arpu) as arpu_sum, count(user_id) as visitors_count")
                    .order("visitors_count desc, title asc")
  end

  def activity_medium
    @items = @q.result.joins(:activity).group("activities.id, visitors.medium")
               .select("title, medium, sum(arpu) as arpu_sum, count(user_id) as visitors_count")
               .order("visitors_count desc, title asc, medium asc")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/activities/index.html.erb
<h1>Activities</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
    </tr>
  </thead>

  <tbody>
    <% @activities.each do |activity| %>
      <tr>
        <td><%= activity.title %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @activities, theme: 'twitter-bootstrap-3' %>

app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @activity.title %>
</p>

<p>
  <strong>Arpu:</strong>
  <%= @activity.arpu %>
</p>

<%= link_to 'Edit', edit_activity_path(@activity) %> |
<%= link_to 'Back', activities_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mateo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/stat/_filter.html.erb
<%= search_form_for @q, url: request.path  do |f| %>
  <%= f.label :medium_eq %>
  <%= f.select :medium_eq, Visitor::CHANNELS.map.each_with_index.to_a, { include_blank: true } %>

  <%= f.label :activity_title_cont_any_of_string %>
  <%= f.search_field :activity_title_cont_any_of_string %>

  <%= f.submit %>
<% end %>

app/views/stat/activity.html.erb
<%= render "filter" %>

<table class="table">
  <thead>
    <tr>
      <th>Product</th>
      <th>Product Detail Views</th>
      <th>Product Revenue</th>
    </tr>
  </thead>
  <tbody>
    <% @activities.each do |ac| %>
      <tr>
        <td><%= ac.title %></td>
        <td><%= ac.visitors_count %></td>
        <td><%= ac.arpu_sum %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/stat/activity_medium.html.erb
<%= render "filter" %>

<table class="table">
  <thead>
    <tr>
      <th>Product</th>
      <th>Medium</th>
      <th>Product Detail Views</th>
      <th>Product Revenue</th>
    </tr>
  </thead>
  <tbody>
    <% @items.each do |i| %>
      <tr>
        <td><%= i.title %></td>
        <td><%= i.medium %></td>
        <td><%= i.visitors_count %></td>
        <td><%= i.arpu_sum %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/stat/medium.html.erb
<%= render "filter" %>

<table class="table">
  <thead>
    <tr>
      <th>Medium</th>
      <th>Product Detail Views</th>
      <th>Product Revenue</th>
    </tr>
  </thead>
  <tbody>
    <% @channels.each do |ch| %>
      <tr>
        <td><%= ch.medium %></td>
        <td><%= ch.visitors_count %></td>
        <td><%= ch.arpu_sum %></td>
      </tr>
    <% end %>
  </tbody>
</table>